# Generated by Django 5.2.6 on 2025-09-19 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowerLimit', models.FloatField(blank=True, default=None, null=True)),
                ('upperLimit', models.FloatField(blank=True, default=None, null=True)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longStartId', models.FloatField()),
                ('latStartId', models.FloatField()),
                ('longEndId', models.FloatField()),
                ('latEndId', models.FloatField()),
                ('length', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('longStartId', 'latStartId', 'longEndId', 'latEndId'), name='Unique Road Segments Constraint')],
            },
        ),
        migrations.CreateModel(
            name='SegmentSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeUpdated', models.DateTimeField(auto_now=True)),
                ('speed', models.FloatField()),
                ('roadSegment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.roadsegment')),
            ],
        ),
    ]
