# Generated by Django 5.2.6 on 2025-09-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roadsegment',
            name='Unique Road Segments Constraint',
        ),
        migrations.RenameField(
            model_name='roadsegment',
            old_name='latEndId',
            new_name='latEnd',
        ),
        migrations.RenameField(
            model_name='roadsegment',
            old_name='latStartId',
            new_name='latStart',
        ),
        migrations.RenameField(
            model_name='roadsegment',
            old_name='longEndId',
            new_name='longEnd',
        ),
        migrations.RenameField(
            model_name='roadsegment',
            old_name='longStartId',
            new_name='longStart',
        ),
        migrations.AddConstraint(
            model_name='roadsegment',
            constraint=models.UniqueConstraint(fields=('longStart', 'latStart', 'longEnd', 'latEnd'), name='Unique Road Segments Constraint'),
        ),
    ]
